default_context:
  project_name: '{{ cookiecutter.project_name }}'
  project_slug: '{{ cookiecutter.project_slug }}'
  backend_cors_origins: '{{ cookiecutter.backend_cors_origins }}'

  postgres_db: '{{ cookiecutter.postgres_db }}'
  postgres_user: '{{ cookiecutter.postgres_user }}'
  postgres_password: '{{ cookiecutter.postgres_password }}'
  postgres_port: '{{ cookiecutter.postgres_port }}'

  smtp_port: '{{ cookiecutter.smtp_port }}'
  smtp_host: '{{ cookiecutter.smtp_host }}'
  smtp_user: '{{ cookiecutter.smtp_user }}'
  smtp_password: '{{ cookiecutter.smtp_password }}'
  smtp_emails_from_email: '{{ cookiecutter.smtp_emails_from_email }}'

  docker_image_prefix: '{{ cookiecutter.docker_image_prefix }}'
  docker_image_backend: '{{ cookiecutter.docker_image_backend }}'
  docker_image_celeryworker: '{{ cookiecutter.docker_image_celeryworker }}'
  docker_image_frontend: '{{ cookiecutter.docker_image_frontend }}'
  _template: ./
