version: "3.9"

services:
  nginx:
    image: nginx:latest
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
      - "5050:5050"
      - "5051:5051"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/home/${DATABASE_USER}/static
      - media_volume:/home/${DATABASE_USER}/media
    depends_on:
      - backend
      - pgadmin

  backend:
    restart: on-failure
    env_file:
      - .env
    build:
      context: ./src/backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV}
        USER: ${{DATABASE_USER}}
#    command: bash -c "./venv/bin/gunicorn --workers 3 --bind 0.0.0.0:8080 backend.wsgi:application"
    depends_on:
      - db
    volumes:
      - static_volume:/home/${DATABASE_USER}/static
      - media_volume:/home/${DATABASE_USER}/media
    ports:
      - "8080:8080"

  celery:
    restart: on-failure
    env_file:
      - .env
    build:
      context: ./src/backend
      dockerfile: celery.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV}
        DATABASE_USER: ${DATABASE_USER}
#    command: bash -c "./venv/bin/celery -A backend worker -l info"
    depends_on:
      - db
      - redis
      - backend
  db:
    image: postgres:latest
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - default
    depends_on:
      - db
    env_file:
      - .env

  dbbackups:
    image: kartoza/pg-backup:13.0
    hostname: pg-backups
    volumes:
      - dbbackups:/backups
    ports:
      - "5433:5432"
    environment:
      - DUMPPREFIX=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASS=${DATABASE_PASSWORD}
      - POSTGRES_PORT=${DATABASE_PORT}
      - POSTGRES_HOST=db
      - POSTGRES_DBNAME=${DATABASE_NAME}
    restart: on-failure
    depends_on:
      - db

  redis:
    image: redis:alpine
    restart: on-failure
    ports:
      - "6379:6379"

volumes:
  dbbackups:
  postgres_data:
  static_volume:
  media_volume:
